theme:
  name: material
  feature:
    tabs: true
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.instant
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugings
plugings:
  - search
  - tags: 
    enabled: true
  - blog:
    enabled: true
    authors: false
  - minify:
      minify_html: true

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - toc:
      permalink: true
      toc_depth: 3

site_name: Insights by Manikanth
site_url: https://manikanthr5.github.io/insights
copyright: Copyright &copy; 2022 @manikanthr5

# Page Tree
nav:
  - Home: index.md 
  - Data Science: 
    - Data Science: data-science/index.md 
    - Data Science Basics: data-science/basics/index.md 
    - Data Science Advanced: data-science/advanced/index.md 
  - Deep Learning: 
    - Deep Learning: deep-learning/index.md 
    - Deep Learning Basics: deep-learning/basics/index.md 
    - Deep Learning Basics: deep-learning/advanced/index.md 
  - Kaggle: kaggle/index.md 
  - Blog: blog/index.md 

